CREATE TYPE user_role AS ENUM ('ADMIN', 'MANAGER', 'STAFF', 'TENANT', 'RESTAURANT_STAFF')

CREATE TYPE gender AS ENUM ('MALE', 'FEMALE')

CREATE TYPE user_status AS ENUM ('ACTIVE', 'INACTIVE', 'PENDING', 'LOCKED', 'DELETED')

CREATE TABLE users (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	role	user_role NOT NULL,
	phone	VARCHAR(20) UNIQUE,
	identity VARCHAR(20) UNIQUE,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	gender gender NOT NULL,
	birthdate TIMESTAMPTZ NOT NULL,
	postal_code VARCHAR(10),
	address VARCHAR(300),
	profile_image TEXT,
	status user_status NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)
