CREATE TYPE user_role AS ENUM ('ADMIN', 'MANAGER', 'STAFF', 'TENANT', 'RESTAURANT_STAFF')

CREATE TYPE gender AS ENUM ('MALE', 'FEMALE')

CREATE TYPE user_status AS ENUM ('ACTIVE', 'INACTIVE', 'PENDING', 'LOCKED', 'DELETED')

CREATE TABLE users (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	role	user_role NOT NULL,
	phone	VARCHAR(20) UNIQUE,
	identity VARCHAR(20) UNIQUE,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	gender gender NOT NULL,
	birthdate TIMESTAMPTZ NOT NULL,
	postal_code VARCHAR(10),
	address VARCHAR(300),
	profile_image TEXT,
	status user_status NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TYPE tenant_type AS ENUM ('PERSONAL', 'BUSINESS')

CREATE TABLE tenants (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	code VARCHAR(50) UNIQUE NOT NULL,
	description TEXT,
	type tenant_type NOT NULL,
	notes VARCHAR(255),
	user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
)


CREATE TABLE sub_packages (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) UNIQUE NOT NULL,
	description TEXT,
	duration_month INT NOT NULL,
	price DECIMAL(18,2) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	image TEXT
)

CREATE TYPE restaurant_type AS ENUM ('FOOD', 'BEVERAGE', 'FB')

CREATE TABLE restaurants (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	location VARCHAR(512) NOT NULL,
	description TEXT,
	contact_email VARCHAR(255),
	contact_phone VARCHAR(20),
	postal_code VARCHAR(20),
	type restaurant_type NOT NULL,
	avg_rating DECIMAL(2,1) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	notes VARCHAR(255),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	sub_package_id BIGINT NOT NULL REFERENCES sub_packages(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON UPDATE CASCADE ON DELETE CASCADE
)


CREATE TABLE restaurant_images (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	image TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TYPE order_status AS ENUM ('PENDING', 'COMPLETED', 'CANCELED')

CREATE TABLE orders (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	order_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status order_status NOT NULL,
	amount DECIMAL(18,2) NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	sub_package_id BIGINT NOT NULL REFERENCES sub_packages(id) ON UPDATE CASCADE ON DELETE RESTRICT
)

