// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"context"
	"embed"
	"errors"
	"fmt"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/introspection"
	"github.com/nhatflash/fbchain/graph/model"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{
		schema:     cfg.Schema,
		resolvers:  cfg.Resolvers,
		directives: cfg.Directives,
		complexity: cfg.Complexity,
	}
}

type Config struct {
	Schema     *ast.Schema
	Resolvers  ResolverRoot
	Directives DirectiveRoot
	Complexity ComplexityRoot
}

type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
	Restaurant() RestaurantResolver
	RestaurantImage() RestaurantImageResolver
	RestaurantItem() RestaurantItemResolver
	Tenant() TenantResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	Mutation struct {
		CreateTodo func(childComplexity int, input model.NewTodo) int
	}

	Query struct {
		Me               func(childComplexity int) int
		Restaurant       func(childComplexity int, id string) int
		RestaurantImage  func(childComplexity int, id string) int
		RestaurantImages func(childComplexity int) int
		RestaurantItem   func(childComplexity int, id string) int
		RestaurantItems  func(childComplexity int) int
		Restaurants      func(childComplexity int) int
		Tenant           func(childComplexity int, id string) int
		Tenants          func(childComplexity int) int
		User             func(childComplexity int, id string) int
		Users            func(childComplexity int) int
	}

	Restaurant struct {
		AvgRating    func(childComplexity int) int
		ContactEmail func(childComplexity int) int
		ContactPhone func(childComplexity int) int
		Description  func(childComplexity int) int
		ID           func(childComplexity int) int
		Images       func(childComplexity int) int
		IsActive     func(childComplexity int) int
		Items        func(childComplexity int) int
		Location     func(childComplexity int) int
		Name         func(childComplexity int) int
		Notes        func(childComplexity int) int
		PostalCode   func(childComplexity int) int
		Tenant       func(childComplexity int) int
		TenantID     func(childComplexity int) int
		Type         func(childComplexity int) int
	}

	RestaurantImage struct {
		CreatedAt    func(childComplexity int) int
		ID           func(childComplexity int) int
		Image        func(childComplexity int) int
		Restaurant   func(childComplexity int) int
		RestaurantID func(childComplexity int) int
	}

	RestaurantItem struct {
		Description  func(childComplexity int) int
		ID           func(childComplexity int) int
		Image        func(childComplexity int) int
		Name         func(childComplexity int) int
		Notes        func(childComplexity int) int
		Price        func(childComplexity int) int
		Restaurant   func(childComplexity int) int
		RestaurantID func(childComplexity int) int
		Status       func(childComplexity int) int
		Type         func(childComplexity int) int
	}

	Tenant struct {
		Code        func(childComplexity int) int
		Description func(childComplexity int) int
		ID          func(childComplexity int) int
		Notes       func(childComplexity int) int
		Restaurants func(childComplexity int) int
		Type        func(childComplexity int) int
		User        func(childComplexity int) int
		UserID      func(childComplexity int) int
	}

	Todo struct {
		Done func(childComplexity int) int
		ID   func(childComplexity int) int
		Text func(childComplexity int) int
		User func(childComplexity int) int
	}

	User struct {
		Address      func(childComplexity int) int
		Birthdate    func(childComplexity int) int
		Email        func(childComplexity int) int
		FirstName    func(childComplexity int) int
		Gender       func(childComplexity int) int
		ID           func(childComplexity int) int
		Identity     func(childComplexity int) int
		LastName     func(childComplexity int) int
		Phone        func(childComplexity int) int
		PostalCode   func(childComplexity int) int
		ProfileImage func(childComplexity int) int
	}
}

type executableSchema struct {
	schema     *ast.Schema
	resolvers  ResolverRoot
	directives DirectiveRoot
	complexity ComplexityRoot
}

func (e *executableSchema) Schema() *ast.Schema {
	if e.schema != nil {
		return e.schema
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := executionContext{nil, e, 0, 0, nil}
	_ = ec
	switch typeName + "." + field {

	case "Mutation.createTodo":
		if e.complexity.Mutation.CreateTodo == nil {
			break
		}

		args, err := ec.field_Mutation_createTodo_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateTodo(childComplexity, args["input"].(model.NewTodo)), true

	case "Query.me":
		if e.complexity.Query.Me == nil {
			break
		}

		return e.complexity.Query.Me(childComplexity), true

	case "Query.restaurant":
		if e.complexity.Query.Restaurant == nil {
			break
		}

		args, err := ec.field_Query_restaurant_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.Restaurant(childComplexity, args["id"].(string)), true

	case "Query.restaurantImage":
		if e.complexity.Query.RestaurantImage == nil {
			break
		}

		args, err := ec.field_Query_restaurantImage_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.RestaurantImage(childComplexity, args["id"].(string)), true

	case "Query.restaurantImages":
		if e.complexity.Query.RestaurantImages == nil {
			break
		}

		return e.complexity.Query.RestaurantImages(childComplexity), true

	case "Query.restaurantItem":
		if e.complexity.Query.RestaurantItem == nil {
			break
		}

		args, err := ec.field_Query_restaurantItem_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.RestaurantItem(childComplexity, args["id"].(string)), true

	case "Query.restaurantItems":
		if e.complexity.Query.RestaurantItems == nil {
			break
		}

		return e.complexity.Query.RestaurantItems(childComplexity), true

	case "Query.restaurants":
		if e.complexity.Query.Restaurants == nil {
			break
		}

		return e.complexity.Query.Restaurants(childComplexity), true

	case "Query.tenant":
		if e.complexity.Query.Tenant == nil {
			break
		}

		args, err := ec.field_Query_tenant_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.Tenant(childComplexity, args["id"].(string)), true

	case "Query.tenants":
		if e.complexity.Query.Tenants == nil {
			break
		}

		return e.complexity.Query.Tenants(childComplexity), true

	case "Query.user":
		if e.complexity.Query.User == nil {
			break
		}

		args, err := ec.field_Query_user_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.User(childComplexity, args["id"].(string)), true

	case "Query.users":
		if e.complexity.Query.Users == nil {
			break
		}

		return e.complexity.Query.Users(childComplexity), true

	case "Restaurant.avgRating":
		if e.complexity.Restaurant.AvgRating == nil {
			break
		}

		return e.complexity.Restaurant.AvgRating(childComplexity), true

	case "Restaurant.contactEmail":
		if e.complexity.Restaurant.ContactEmail == nil {
			break
		}

		return e.complexity.Restaurant.ContactEmail(childComplexity), true

	case "Restaurant.contactPhone":
		if e.complexity.Restaurant.ContactPhone == nil {
			break
		}

		return e.complexity.Restaurant.ContactPhone(childComplexity), true

	case "Restaurant.description":
		if e.complexity.Restaurant.Description == nil {
			break
		}

		return e.complexity.Restaurant.Description(childComplexity), true

	case "Restaurant.id":
		if e.complexity.Restaurant.ID == nil {
			break
		}

		return e.complexity.Restaurant.ID(childComplexity), true

	case "Restaurant.images":
		if e.complexity.Restaurant.Images == nil {
			break
		}

		return e.complexity.Restaurant.Images(childComplexity), true

	case "Restaurant.isActive":
		if e.complexity.Restaurant.IsActive == nil {
			break
		}

		return e.complexity.Restaurant.IsActive(childComplexity), true

	case "Restaurant.items":
		if e.complexity.Restaurant.Items == nil {
			break
		}

		return e.complexity.Restaurant.Items(childComplexity), true

	case "Restaurant.location":
		if e.complexity.Restaurant.Location == nil {
			break
		}

		return e.complexity.Restaurant.Location(childComplexity), true

	case "Restaurant.name":
		if e.complexity.Restaurant.Name == nil {
			break
		}

		return e.complexity.Restaurant.Name(childComplexity), true

	case "Restaurant.notes":
		if e.complexity.Restaurant.Notes == nil {
			break
		}

		return e.complexity.Restaurant.Notes(childComplexity), true

	case "Restaurant.postalCode":
		if e.complexity.Restaurant.PostalCode == nil {
			break
		}

		return e.complexity.Restaurant.PostalCode(childComplexity), true

	case "Restaurant.tenant":
		if e.complexity.Restaurant.Tenant == nil {
			break
		}

		return e.complexity.Restaurant.Tenant(childComplexity), true

	case "Restaurant.tenantId":
		if e.complexity.Restaurant.TenantID == nil {
			break
		}

		return e.complexity.Restaurant.TenantID(childComplexity), true

	case "Restaurant.type":
		if e.complexity.Restaurant.Type == nil {
			break
		}

		return e.complexity.Restaurant.Type(childComplexity), true

	case "RestaurantImage.createdAt":
		if e.complexity.RestaurantImage.CreatedAt == nil {
			break
		}

		return e.complexity.RestaurantImage.CreatedAt(childComplexity), true

	case "RestaurantImage.id":
		if e.complexity.RestaurantImage.ID == nil {
			break
		}

		return e.complexity.RestaurantImage.ID(childComplexity), true

	case "RestaurantImage.image":
		if e.complexity.RestaurantImage.Image == nil {
			break
		}

		return e.complexity.RestaurantImage.Image(childComplexity), true

	case "RestaurantImage.restaurant":
		if e.complexity.RestaurantImage.Restaurant == nil {
			break
		}

		return e.complexity.RestaurantImage.Restaurant(childComplexity), true

	case "RestaurantImage.restaurantId":
		if e.complexity.RestaurantImage.RestaurantID == nil {
			break
		}

		return e.complexity.RestaurantImage.RestaurantID(childComplexity), true

	case "RestaurantItem.description":
		if e.complexity.RestaurantItem.Description == nil {
			break
		}

		return e.complexity.RestaurantItem.Description(childComplexity), true

	case "RestaurantItem.id":
		if e.complexity.RestaurantItem.ID == nil {
			break
		}

		return e.complexity.RestaurantItem.ID(childComplexity), true

	case "RestaurantItem.image":
		if e.complexity.RestaurantItem.Image == nil {
			break
		}

		return e.complexity.RestaurantItem.Image(childComplexity), true

	case "RestaurantItem.name":
		if e.complexity.RestaurantItem.Name == nil {
			break
		}

		return e.complexity.RestaurantItem.Name(childComplexity), true

	case "RestaurantItem.notes":
		if e.complexity.RestaurantItem.Notes == nil {
			break
		}

		return e.complexity.RestaurantItem.Notes(childComplexity), true

	case "RestaurantItem.price":
		if e.complexity.RestaurantItem.Price == nil {
			break
		}

		return e.complexity.RestaurantItem.Price(childComplexity), true

	case "RestaurantItem.restaurant":
		if e.complexity.RestaurantItem.Restaurant == nil {
			break
		}

		return e.complexity.RestaurantItem.Restaurant(childComplexity), true

	case "RestaurantItem.restaurantId":
		if e.complexity.RestaurantItem.RestaurantID == nil {
			break
		}

		return e.complexity.RestaurantItem.RestaurantID(childComplexity), true

	case "RestaurantItem.status":
		if e.complexity.RestaurantItem.Status == nil {
			break
		}

		return e.complexity.RestaurantItem.Status(childComplexity), true

	case "RestaurantItem.type":
		if e.complexity.RestaurantItem.Type == nil {
			break
		}

		return e.complexity.RestaurantItem.Type(childComplexity), true

	case "Tenant.code":
		if e.complexity.Tenant.Code == nil {
			break
		}

		return e.complexity.Tenant.Code(childComplexity), true

	case "Tenant.description":
		if e.complexity.Tenant.Description == nil {
			break
		}

		return e.complexity.Tenant.Description(childComplexity), true

	case "Tenant.id":
		if e.complexity.Tenant.ID == nil {
			break
		}

		return e.complexity.Tenant.ID(childComplexity), true

	case "Tenant.notes":
		if e.complexity.Tenant.Notes == nil {
			break
		}

		return e.complexity.Tenant.Notes(childComplexity), true

	case "Tenant.restaurants":
		if e.complexity.Tenant.Restaurants == nil {
			break
		}

		return e.complexity.Tenant.Restaurants(childComplexity), true

	case "Tenant.type":
		if e.complexity.Tenant.Type == nil {
			break
		}

		return e.complexity.Tenant.Type(childComplexity), true

	case "Tenant.user":
		if e.complexity.Tenant.User == nil {
			break
		}

		return e.complexity.Tenant.User(childComplexity), true

	case "Tenant.userId":
		if e.complexity.Tenant.UserID == nil {
			break
		}

		return e.complexity.Tenant.UserID(childComplexity), true

	case "Todo.done":
		if e.complexity.Todo.Done == nil {
			break
		}

		return e.complexity.Todo.Done(childComplexity), true

	case "Todo.id":
		if e.complexity.Todo.ID == nil {
			break
		}

		return e.complexity.Todo.ID(childComplexity), true

	case "Todo.text":
		if e.complexity.Todo.Text == nil {
			break
		}

		return e.complexity.Todo.Text(childComplexity), true

	case "Todo.user":
		if e.complexity.Todo.User == nil {
			break
		}

		return e.complexity.Todo.User(childComplexity), true

	case "User.address":
		if e.complexity.User.Address == nil {
			break
		}

		return e.complexity.User.Address(childComplexity), true

	case "User.birthdate":
		if e.complexity.User.Birthdate == nil {
			break
		}

		return e.complexity.User.Birthdate(childComplexity), true

	case "User.email":
		if e.complexity.User.Email == nil {
			break
		}

		return e.complexity.User.Email(childComplexity), true

	case "User.firstName":
		if e.complexity.User.FirstName == nil {
			break
		}

		return e.complexity.User.FirstName(childComplexity), true

	case "User.gender":
		if e.complexity.User.Gender == nil {
			break
		}

		return e.complexity.User.Gender(childComplexity), true

	case "User.id":
		if e.complexity.User.ID == nil {
			break
		}

		return e.complexity.User.ID(childComplexity), true

	case "User.identity":
		if e.complexity.User.Identity == nil {
			break
		}

		return e.complexity.User.Identity(childComplexity), true

	case "User.lastName":
		if e.complexity.User.LastName == nil {
			break
		}

		return e.complexity.User.LastName(childComplexity), true

	case "User.phone":
		if e.complexity.User.Phone == nil {
			break
		}

		return e.complexity.User.Phone(childComplexity), true

	case "User.postalCode":
		if e.complexity.User.PostalCode == nil {
			break
		}

		return e.complexity.User.PostalCode(childComplexity), true

	case "User.profileImage":
		if e.complexity.User.ProfileImage == nil {
			break
		}

		return e.complexity.User.ProfileImage(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := executionContext{opCtx, e, 0, 0, make(chan graphql.DeferredResult)}
	inputUnmarshalMap := graphql.BuildUnmarshalerMap(
		ec.unmarshalInputNewTodo,
	)
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.pendingDeferred) > 0 {
					result := <-ec.deferredResults
					atomic.AddInt32(&ec.pendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.pendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}
	case ast.Mutation:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Mutation(ctx, opCtx.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.OperationContext
	*executableSchema
	deferred        int32
	pendingDeferred int32
	deferredResults chan graphql.DeferredResult
}

func (ec *executionContext) processDeferredGroup(dg graphql.DeferredGroup) {
	atomic.AddInt32(&ec.pendingDeferred, 1)
	go func() {
		ctx := graphql.WithFreshResponseContext(dg.Context)
		dg.FieldSet.Dispatch(ctx)
		ds := graphql.DeferredResult{
			Path:   dg.Path,
			Label:  dg.Label,
			Result: dg.FieldSet,
			Errors: graphql.GetErrors(ctx),
		}
		// null fields should bubble up
		if dg.FieldSet.Invalids > 0 {
			ds.Result = graphql.Null
		}
		ec.deferredResults <- ds
	}()
}

func (ec *executionContext) introspectSchema() (*introspection.Schema, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapSchema(ec.Schema()), nil
}

func (ec *executionContext) introspectType(name string) (*introspection.Type, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapTypeFromDef(ec.Schema(), ec.Schema().Types[name]), nil
}

//go:embed "schema.graphqls"
var sourcesFS embed.FS

func sourceData(filename string) string {
	data, err := sourcesFS.ReadFile(filename)
	if err != nil {
		panic(fmt.Sprintf("codegen problem: %s not available", filename))
	}
	return string(data)
}

var sources = []*ast.Source{
	{Name: "schema.graphqls", Input: sourceData("schema.graphqls"), BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)
