package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"strconv"
	appErr "github.com/nhatflash/fbchain/error"
	gqlModel "github.com/nhatflash/fbchain/graph/model"
	"github.com/nhatflash/fbchain/middleware"
	"github.com/nhatflash/fbchain/model"
	"github.com/nhatflash/fbchain/security"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input gqlModel.NewTodo) (*gqlModel.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*gqlModel.User, error) {
	claims, ok := ctx.Value(middleware.UserKey{}).(*security.JwtAccessClaims)
	if !ok || claims == nil {
		return nil, appErr.UnauthorizedError("Authentication is required.")
	}
	u, err := r.UserService.GetUserById(ctx, claims.UserId)
	if err != nil {
		return nil, err
	}
	return MapToGqlModelUser(u), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*gqlModel.User, error) {
	var err error
	// user, ok := ctx.Value(middleware.UserKey{}).(*security.JwtAccessClaims)
	// if !ok || user == nil {
	// 	return nil, appErr.UnauthorizedError("Authentication is required.")
	// }

	var users []model.User
	users, err = r.UserService.GetListUser(ctx)
	if err != nil {
		return nil, err
	}
	var gqlUsers []*gqlModel.User
	for _, u := range users {
		var gqlU = MapToGqlModelUser(&u)
		gqlUsers = append(gqlUsers, gqlU)
	}
	return gqlUsers, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*gqlModel.User, error) {
	var err error
	var userId int64
	userId, err = strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}
	var u *model.User
	u, err = r.UserService.GetUserById(ctx, userId)
	if err != nil {
		return nil, err
	}
	return MapToGqlModelUser(u), nil
}

// Tenants is the resolver for the tenants field.
func (r *queryResolver) Tenants(ctx context.Context) ([]*gqlModel.Tenant, error) {
	t, err := r.TenantService.GetListTenant(ctx)
	if err != nil {
		return nil, err
	}
	var tenants []*gqlModel.Tenant
	for _, tenant := range t {
		tn := MapToGqlModelTenant(&tenant)
		tenants = append(tenants, tn)
	}
	return tenants, nil
}

// Tenant is the resolver for the tenant field.
func (r *queryResolver) Tenant(ctx context.Context, id string) (*gqlModel.Tenant, error) {
	var err error
	var tenantId int64
	tenantId, err = strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}
	var t *model.Tenant
	t, err = r.TenantService.GetTenantById(ctx, tenantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlModelTenant(t), nil
}

// Restaurants is the resolver for the restaurants field.
func (r *queryResolver) Restaurants(ctx context.Context) ([]*gqlModel.Restaurant, error) {
	restaurants, err := r.RestaurantService.GetAllRestaurants(ctx)
	if err != nil {
		return nil, err
	}
	var gqlRestaurants []*gqlModel.Restaurant
	for _, res := range restaurants {
		gqlRes := MapToGqlRestaurant(&res)
		gqlRestaurants = append(gqlRestaurants, gqlRes)
	}
	return gqlRestaurants, nil
}

// Restaurant is the resolver for the restaurant field.
func (r *queryResolver) Restaurant(ctx context.Context, id string) (*gqlModel.Restaurant, error) {
	var err error
	var restaurantId int64
	restaurantId, err = strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}
	var res *model.Restaurant
	res, err = r.RestaurantService.GetRestaurantById(ctx, restaurantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurant(res), nil
}

// RestaurantImages is the resolver for the restaurantImages field.
func (r *queryResolver) RestaurantImages(ctx context.Context) ([]*gqlModel.RestaurantImage, error) {
	imgs, err := r.RestaurantService.GetAllRestaurantImages(ctx)
	if err != nil {
		return nil, err
	}
	var gqlRImgs []*gqlModel.RestaurantImage
	for _, img := range imgs {
		gqlRImg := MapToGqlRestaurantImage(&img)
		gqlRImgs = append(gqlRImgs, gqlRImg)
	}
	return gqlRImgs, nil
}

// RestaurantImage is the resolver for the restaurantImage field.
func (r *queryResolver) RestaurantImage(ctx context.Context, id string) (*gqlModel.RestaurantImage, error) {
	var err error
	var imgId int64
	imgId, err = strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}
	var img *model.RestaurantImage
	img, err = r.RestaurantService.GetRestaurantImageById(ctx, imgId)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurantImage(img), nil
}

// Tenant is the resolver for the tenant field.
func (r *restaurantResolver) Tenant(ctx context.Context, obj *gqlModel.Restaurant) (*gqlModel.Tenant, error) {
	var tenantId int64
	var err error
	tenantId, err = strconv.ParseInt(*obj.TenantID, 10, 64)
	if err != nil {
		return nil, err
	}
	var t *model.Tenant
	t, err = r.TenantService.GetTenantById(ctx, tenantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlModelTenant(t), nil
}

// Images is the resolver for the images field.
func (r *restaurantResolver) Images(ctx context.Context, obj *gqlModel.Restaurant) ([]*gqlModel.RestaurantImage, error) {
	var restaurantId int64
	var err error
	restaurantId, err = strconv.ParseInt(obj.ID, 10, 64)
	if err != nil {
		return nil, err
	}
	var imgs []model.RestaurantImage
	imgs, err = r.RestaurantService.GetRestaurantImages(ctx, restaurantId)
	if err != nil {
		return nil, err
	}
	var gqlRImgs []*gqlModel.RestaurantImage
	for _, img := range imgs {
		gqlRImg := MapToGqlRestaurantImage(&img)
		gqlRImgs = append(gqlRImgs, gqlRImg)
	}
	return gqlRImgs, nil
}

// Restaurant is the resolver for the restaurant field.
func (r *restaurantImageResolver) Restaurant(ctx context.Context, obj *gqlModel.RestaurantImage) (*gqlModel.Restaurant, error) {
	var restaurantId int64
	var err error
	restaurantId, err = strconv.ParseInt(*obj.RestaurantID, 10, 64)
	if err != nil {
		return nil, err
	}
	var res *model.Restaurant
	res, err = r.RestaurantService.GetRestaurantById(ctx, restaurantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurant(res), nil
}

// User is the resolver for the user field.
func (r *tenantResolver) User(ctx context.Context, obj *gqlModel.Tenant) (*gqlModel.User, error) {
	var err error
	var userId int64
	userId, err = strconv.ParseInt(*obj.UserID, 10, 64)
	if err != nil {
		return nil, err
	}
	var u *model.User
	u, err = r.UserService.GetUserById(ctx, userId)
	if err != nil {
		return nil, err
	}
	return MapToGqlModelUser(u), nil
}

// Restaurants is the resolver for the restaurants field.
func (r *tenantResolver) Restaurants(ctx context.Context, obj *gqlModel.Tenant) ([]*gqlModel.Restaurant, error) {
	var err error
	var tenantId int64
	tenantId, err = strconv.ParseInt(obj.ID, 10, 64)
	if err != nil {
		return nil, err
	}
	var restaurants []model.Restaurant
	restaurants, err = r.RestaurantService.GetRestaurantsByTenantId(ctx, tenantId)
	if err != nil {
		return nil, err
	}
	var gqlRestaurants []*gqlModel.Restaurant
	for _, rtr := range restaurants {
		gqlRtr := MapToGqlRestaurant(&rtr)
		gqlRestaurants = append(gqlRestaurants, gqlRtr)
	}
	return gqlRestaurants, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Restaurant returns RestaurantResolver implementation.
func (r *Resolver) Restaurant() RestaurantResolver { return &restaurantResolver{r} }

// RestaurantImage returns RestaurantImageResolver implementation.
func (r *Resolver) RestaurantImage() RestaurantImageResolver { return &restaurantImageResolver{r} }

// Tenant returns TenantResolver implementation.
func (r *Resolver) Tenant() TenantResolver { return &tenantResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type restaurantResolver struct{ *Resolver }
type restaurantImageResolver struct{ *Resolver }
type tenantResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) ChangeProfile(ctx context.Context, input gqlModel.UpdateProfile) (*gqlModel.User, error) {
	firstName := input.FirstName
	lastName :=
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*gqlModel.User, error) {
	claims, ok := ctx.Value(middleware.UserKey{}).(*security.JwtAccessClaims)
	if !ok || claims == nil {
		return nil, appErr.UnauthorizedError("Authentication is required.")
	}
	u, err := r.UserService.GetUserById(claims.UserId)
	if err != nil {
		return nil, err
	}
	return MapToGqlModelUser(u), nil
}
*/
