package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"strconv"

	appErr "github.com/nhatflash/fbchain/error"
	gqlModel "github.com/nhatflash/fbchain/graph/model"
	"github.com/nhatflash/fbchain/middleware"
	"github.com/nhatflash/fbchain/model"
	"github.com/nhatflash/fbchain/security"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input gqlModel.NewTodo) (*gqlModel.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// Tenant is the resolver for the tenant field.
func (r *orderResolver) Tenant(ctx context.Context, obj *gqlModel.Order) (*gqlModel.Tenant, error) {
	var tenantId int64
	var err error
	tenantId, err = strconv.ParseInt(*obj.TenantID, 10, 64)
	if err != nil {
		return nil, err
	}
	var t *model.Tenant
	t, err = r.TenantService.FindTenantById(ctx, tenantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlTenant(t), nil
}

// Restaurant is the resolver for the restaurant field.
func (r *orderResolver) Restaurant(ctx context.Context, obj *gqlModel.Order) (*gqlModel.Restaurant, error) {
	var restaurantId int64
	var err error
	restaurantId, err = strconv.ParseInt(*obj.RestaurantID, 10, 64)
	if err != nil {
		return nil, err
	}
	var res *model.Restaurant
	res, err = r.RestaurantService.FindRestaurantById(ctx, restaurantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurant(res), nil
}

// SubPackage is the resolver for the subPackage field.
func (r *orderResolver) SubPackage(ctx context.Context, obj *gqlModel.Order) (*gqlModel.SubPackage, error) {
	var subId int64
	var err error
	subId, err = strconv.ParseInt(*obj.SubPackageID, 10, 64)
	if err != nil {
		return nil, err
	}
	var s *model.SubPackage
	s, err = r.SubPackageService.FindSubPackageById(ctx, subId)
	if err != nil {
		return nil, err
	}
	return MapToGqlSubPackage(s), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*gqlModel.User, error) {
	claims, ok := ctx.Value(middleware.UserKey{}).(*security.JwtAccessClaims)
	if !ok || claims == nil {
		return nil, appErr.UnauthorizedError("Authentication is required.")
	}
	u, err := r.UserService.FindUserById(ctx, claims.UserId)
	if err != nil {
		return nil, err
	}
	return MapToGqlUser(u), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*gqlModel.User, error) {
	var err error
	var users []model.User
	users, err = r.UserService.FindAllUsers(ctx)
	if err != nil {
		return nil, err
	}
	return MapToGqlUsers(users), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*gqlModel.User, error) {
	var err error
	var userId int64
	userId, err = strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}
	var u *model.User
	u, err = r.UserService.FindUserById(ctx, userId)
	if err != nil {
		return nil, err
	}
	return MapToGqlUser(u), nil
}

// Tenants is the resolver for the tenants field.
func (r *queryResolver) Tenants(ctx context.Context) ([]*gqlModel.Tenant, error) {
	tenants, err := r.TenantService.FindAllTenants(ctx)
	if err != nil {
		return nil, err
	}
	return MapToGqlTenants(tenants), nil
}

// Tenant is the resolver for the tenant field.
func (r *queryResolver) Tenant(ctx context.Context, id string) (*gqlModel.Tenant, error) {
	var err error
	var tenantId int64
	tenantId, err = strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}
	var t *model.Tenant
	t, err = r.TenantService.FindTenantById(ctx, tenantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlTenant(t), nil
}

// Restaurants is the resolver for the restaurants field.
func (r *queryResolver) Restaurants(ctx context.Context) ([]*gqlModel.Restaurant, error) {
	restaurants, err := r.RestaurantService.FindAllRestaurants(ctx)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurants(restaurants), nil
}

// Restaurant is the resolver for the restaurant field.
func (r *queryResolver) Restaurant(ctx context.Context, id string) (*gqlModel.Restaurant, error) {
	var err error
	var restaurantId int64
	restaurantId, err = strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}
	var res *model.Restaurant
	res, err = r.RestaurantService.FindRestaurantById(ctx, restaurantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurant(res), nil
}

// RestaurantImages is the resolver for the restaurantImages field.
func (r *queryResolver) RestaurantImages(ctx context.Context) ([]*gqlModel.RestaurantImage, error) {
	imgs, err := r.RestaurantService.FindAllRestaurantImages(ctx)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurantImages(imgs), nil
}

// RestaurantImage is the resolver for the restaurantImage field.
func (r *queryResolver) RestaurantImage(ctx context.Context, id string) (*gqlModel.RestaurantImage, error) {
	var err error
	var imgId int64
	imgId, err = strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}
	var img *model.RestaurantImage
	img, err = r.RestaurantService.FindRestaurantImageById(ctx, imgId)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurantImage(img), nil
}

// RestaurantItems is the resolver for the restaurantItems field.
func (r *queryResolver) RestaurantItems(ctx context.Context) ([]*gqlModel.RestaurantItem, error) {
	items, err := r.RestaurantService.FindAllRestaurantItems(ctx)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurantItems(items), nil
}

// RestaurantItem is the resolver for the restaurantItem field.
func (r *queryResolver) RestaurantItem(ctx context.Context, id string) (*gqlModel.RestaurantItem, error) {
	var item *model.RestaurantItem
	var err error
	item, err = r.RestaurantService.FindRestaurantItemById(ctx, id)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurantItem(item), nil
}

// RestaurantTables is the resolver for the restaurantTables field.
func (r *queryResolver) RestaurantTables(ctx context.Context) ([]*gqlModel.RestaurantTable, error) {
	tables, err := r.RestaurantService.FindAllRestaurantTables(ctx)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurantTables(tables), nil
}

// RestaurantTable is the resolver for the restaurantTable field.
func (r *queryResolver) RestaurantTable(ctx context.Context, id string) (*gqlModel.RestaurantTable, error) {
	var err error
	var tableId int64
	tableId, err = strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}
	var table *model.RestaurantTable
	table, err = r.RestaurantService.FindRestaurantTableById(ctx, tableId)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurantTable(table), nil
}

// SubPackages is the resolver for the subPackages field.
func (r *queryResolver) SubPackages(ctx context.Context) ([]*gqlModel.SubPackage, error) {
	s, err := r.SubPackageService.FindAllSubPackages(ctx)
	if err != nil {
		return nil, err
	}
	return MapToGqlSubPackages(s), nil
}

// SubPackage is the resolver for the subPackage field.
func (r *queryResolver) SubPackage(ctx context.Context, id string) (*gqlModel.SubPackage, error) {
	var subId int64
	var err error
	subId, err = strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}
	var s *model.SubPackage
	s, err = r.SubPackageService.FindSubPackageById(ctx, subId)
	if err != nil {
		return nil, err
	}
	return MapToGqlSubPackage(s), nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*gqlModel.Order, error) {
	o, err := r.OrderService.FindAllOrders(ctx)
	if err != nil {
		return nil, err
	}
	return MapToGqlOrders(o), nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*gqlModel.Order, error) {
	var orderId int64
	var err error
	orderId, err = strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}
	var o *model.Order
	o, err = r.OrderService.FindOrderById(ctx, orderId)
	if err != nil {
		return nil, err
	}
	return MapToGqlOrder(o), nil
}

// Tenant is the resolver for the tenant field.
func (r *restaurantResolver) Tenant(ctx context.Context, obj *gqlModel.Restaurant) (*gqlModel.Tenant, error) {
	var tenantId int64
	var err error
	tenantId, err = strconv.ParseInt(*obj.TenantID, 10, 64)
	if err != nil {
		return nil, err
	}
	var t *model.Tenant
	t, err = r.TenantService.FindTenantById(ctx, tenantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlTenant(t), nil
}

// Images is the resolver for the images field.
func (r *restaurantResolver) Images(ctx context.Context, obj *gqlModel.Restaurant) ([]*gqlModel.RestaurantImage, error) {
	var restaurantId int64
	var err error
	restaurantId, err = strconv.ParseInt(obj.ID, 10, 64)
	if err != nil {
		return nil, err
	}
	var imgs []model.RestaurantImage
	imgs, err = r.RestaurantService.FindRestaurantImagesByRestaurantId(ctx, restaurantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurantImages(imgs), nil
}

// Items is the resolver for the items field.
func (r *restaurantResolver) Items(ctx context.Context, obj *gqlModel.Restaurant) ([]*gqlModel.RestaurantItem, error) {
	var restaurantId int64
	var err error
	restaurantId, err = strconv.ParseInt(obj.ID, 10, 64)
	if err != nil {
		return nil, err
	}
	var items []model.RestaurantItem
	items, err = r.RestaurantService.FindItemsByRestaurantId(ctx, restaurantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurantItems(items), nil
}

// Restaurant is the resolver for the restaurant field.
func (r *restaurantImageResolver) Restaurant(ctx context.Context, obj *gqlModel.RestaurantImage) (*gqlModel.Restaurant, error) {
	var restaurantId int64
	var err error
	restaurantId, err = strconv.ParseInt(*obj.RestaurantID, 10, 64)
	if err != nil {
		return nil, err
	}
	var res *model.Restaurant
	res, err = r.RestaurantService.FindRestaurantById(ctx, restaurantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurant(res), nil
}

// Restaurant is the resolver for the restaurant field.
func (r *restaurantItemResolver) Restaurant(ctx context.Context, obj *gqlModel.RestaurantItem) (*gqlModel.Restaurant, error) {
	var restaurantId int64
	var err error
	restaurantId, err = strconv.ParseInt(*obj.RestaurantID, 10, 64)
	if err != nil {
		return nil, err
	}
	var res *model.Restaurant
	res, err = r.RestaurantService.FindRestaurantById(ctx, restaurantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurant(res), nil
}

// Restaurant is the resolver for the restaurant field.
func (r *restaurantTableResolver) Restaurant(ctx context.Context, obj *gqlModel.RestaurantTable) (*gqlModel.Restaurant, error) {
	var restaurantId int64
	var err error
	restaurantId, err = strconv.ParseInt(*obj.RestaurantID, 10, 64)
	if err != nil {
		return nil, err
	}
	var res *model.Restaurant
	res, err = r.RestaurantService.FindRestaurantById(ctx, restaurantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlRestaurant(res), nil
}

// User is the resolver for the user field.
func (r *tenantResolver) User(ctx context.Context, obj *gqlModel.Tenant) (*gqlModel.User, error) {
	var err error
	var userId int64
	userId, err = strconv.ParseInt(*obj.UserID, 10, 64)
	if err != nil {
		return nil, err
	}
	var u *model.User
	u, err = r.UserService.FindUserById(ctx, userId)
	if err != nil {
		return nil, err
	}
	return MapToGqlUser(u), nil
}

// Restaurants is the resolver for the restaurants field.
func (r *tenantResolver) Restaurants(ctx context.Context, obj *gqlModel.Tenant) ([]*gqlModel.Restaurant, error) {
	var err error
	var tenantId int64
	tenantId, err = strconv.ParseInt(obj.ID, 10, 64)
	if err != nil {
		return nil, err
	}
	var restaurants []model.Restaurant
	restaurants, err = r.RestaurantService.FindRestaurantsByTenantId(ctx, tenantId)
	if err != nil {
		return nil, err
	}
	var gqlRestaurants []*gqlModel.Restaurant
	for _, rtr := range restaurants {
		gqlRtr := MapToGqlRestaurant(&rtr)
		gqlRestaurants = append(gqlRestaurants, gqlRtr)
	}
	return gqlRestaurants, nil
}

// Orders is the resolver for the orders field.
func (r *tenantResolver) Orders(ctx context.Context, obj *gqlModel.Tenant) ([]*gqlModel.Order, error) {
	var err error
	var tenantId int64
	tenantId, err = strconv.ParseInt(obj.ID, 10, 64)
	if err != nil {
		return nil, err
	}
	var orders []model.Order
	orders, err = r.OrderService.FindOrdersByTenantId(ctx, tenantId)
	if err != nil {
		return nil, err
	}
	return MapToGqlOrders(orders), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Restaurant returns RestaurantResolver implementation.
func (r *Resolver) Restaurant() RestaurantResolver { return &restaurantResolver{r} }

// RestaurantImage returns RestaurantImageResolver implementation.
func (r *Resolver) RestaurantImage() RestaurantImageResolver { return &restaurantImageResolver{r} }

// RestaurantItem returns RestaurantItemResolver implementation.
func (r *Resolver) RestaurantItem() RestaurantItemResolver { return &restaurantItemResolver{r} }

// RestaurantTable returns RestaurantTableResolver implementation.
func (r *Resolver) RestaurantTable() RestaurantTableResolver { return &restaurantTableResolver{r} }

// Tenant returns TenantResolver implementation.
func (r *Resolver) Tenant() TenantResolver { return &tenantResolver{r} }

type mutationResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type restaurantResolver struct{ *Resolver }
type restaurantImageResolver struct{ *Resolver }
type restaurantItemResolver struct{ *Resolver }
type restaurantTableResolver struct{ *Resolver }
type tenantResolver struct{ *Resolver }
