package constant


const USER_VERIFY_PASSWORD_OTP_KEY = "userPasswordChangeOTP:"
const VERIFY_PASSWORD_OTP_EXPIRATION_MIN = 15

const USER_CHANGE_PASSWORD_TIME_KEY = "userPasswordChangeTime:"
const USER_CHANGE_PASSWORD_TIME_VALUE = "true"
const CHANGE_PASSWORD_TIME = 15
