// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/subscription": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Subscription Package API",
                "parameters": [
                    {
                        "description": "CreateSubPackage body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.CreateSubPackageRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Change password API",
                "parameters": [
                    {
                        "description": "ChangePassword body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/change-password/verify": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Get change password OTP API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Verify change password OTP API",
                "parameters": [
                    {
                        "description": "VerifyChangePassword body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.VerifyChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/signin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Sign in API",
                "parameters": [
                    {
                        "description": "SignIn body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.SignInResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Tenant sign up API",
                "parameters": [
                    {
                        "description": "TenantSignUp body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.TenantSignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        },
        "/payment/cash": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Pay order with cash API",
                "parameters": [
                    {
                        "description": "PayOrderWithCash body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.PayOrderWithCashRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        },
        "/payment/online/{method}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Pay order with online payment API",
                "parameters": [
                    {
                        "enum": [
                            "VNPAY"
                        ],
                        "type": "string",
                        "description": "Online method",
                        "name": "method",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "orderId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/profile": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Change Profile API",
                "parameters": [
                    {
                        "description": "UpdateProfile body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        },
        "/restaurant": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create restaurant API",
                "parameters": [
                    {
                        "description": "CreateRestaurant body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.CreateRestaurantRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/restaurant/{restaurantId}/item": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Add New Restaurant Item API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Restaurant ID",
                        "name": "restaurantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AddRestaurantItem body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.AddRestaurantItemRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/tenant/order": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Pay subscription package API",
                "parameters": [
                    {
                        "description": "PaySubPackage body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.PaySubPackageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/client.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        },
        "/tenant/verify": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Complete Tenant Info API",
                "parameters": [
                    {
                        "description": "TenantInfo body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.TenantInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.TenantResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "client.AddRestaurantItemRequest": {
            "type": "object",
            "required": [
                "name",
                "price",
                "type"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/enum.ItemType"
                }
            }
        },
        "client.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "confirmNewPassword",
                "newPassword"
            ],
            "properties": {
                "confirmNewPassword": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                }
            }
        },
        "client.CreateRestaurantRequest": {
            "type": "object",
            "required": [
                "location",
                "name",
                "notes",
                "postalCode",
                "type"
            ],
            "properties": {
                "contactEmail": {
                    "type": "string"
                },
                "contactPhone": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "client.CreateSubPackageRequest": {
            "type": "object",
            "required": [
                "durationMonth",
                "name",
                "price"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "durationMonth": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                }
            }
        },
        "client.OrderResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "orderDate": {
                    "type": "string"
                },
                "restaurantId": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/enum.OrderStatus"
                },
                "tenantId": {
                    "type": "integer"
                }
            }
        },
        "client.PayOrderWithCashRequest": {
            "type": "object",
            "required": [
                "orderId"
            ],
            "properties": {
                "notes": {
                    "type": "string"
                },
                "orderId": {
                    "type": "integer"
                }
            }
        },
        "client.PaySubPackageRequest": {
            "type": "object",
            "required": [
                "restaurantId",
                "subPackageId"
            ],
            "properties": {
                "restaurantId": {
                    "type": "integer"
                },
                "subPackageId": {
                    "type": "integer"
                }
            }
        },
        "client.SignInRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "client.SignInResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "lastLogin": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "client.TenantInfoRequest": {
            "type": "object",
            "required": [
                "address",
                "identity",
                "phone",
                "postalCode",
                "type"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "identity": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "profileImage": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/enum.TenantType"
                }
            }
        },
        "client.TenantResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birthdate": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/enum.Gender"
                },
                "identity": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "profileImage": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/enum.UserStatus"
                },
                "type": {
                    "$ref": "#/definitions/enum.TenantType"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "client.TenantSignUpRequest": {
            "type": "object",
            "required": [
                "birthdate",
                "confirmPassword",
                "email",
                "firstName",
                "gender",
                "lastName",
                "password"
            ],
            "properties": {
                "birthdate": {
                    "type": "string"
                },
                "confirmPassword": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/enum.Gender"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "client.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birthdate": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/enum.Gender"
                },
                "identity": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "profileImage": {
                    "type": "string"
                }
            }
        },
        "client.UserResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birthdate": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/enum.Gender"
                },
                "id": {
                    "type": "integer"
                },
                "identity": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "profileImage": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/enum.Role"
                },
                "status": {
                    "$ref": "#/definitions/enum.UserStatus"
                }
            }
        },
        "client.VerifyChangePasswordRequest": {
            "type": "object",
            "required": [
                "verifiedCode"
            ],
            "properties": {
                "verifiedCode": {
                    "type": "string"
                }
            }
        },
        "enum.Gender": {
            "type": "string",
            "enum": [
                "MALE",
                "FEMALE"
            ],
            "x-enum-varnames": [
                "GENDER_MALE",
                "GENDER_FEMALE"
            ]
        },
        "enum.ItemType": {
            "type": "string",
            "enum": [
                "FOOD",
                "BEVERAGE"
            ],
            "x-enum-varnames": [
                "ITEM_FOOD",
                "ITEM_BEVERAGE"
            ]
        },
        "enum.OrderStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "COMPLETED",
                "CANCELED"
            ],
            "x-enum-varnames": [
                "ORDER_PENDING",
                "ORDER_COMPLETED",
                "ORDER_CANCELED"
            ]
        },
        "enum.Role": {
            "type": "string",
            "enum": [
                "ADMIN",
                "MANAGER",
                "STAFF",
                "TENANT"
            ],
            "x-enum-varnames": [
                "ROLE_ADMIN",
                "ROLE_MANAGER",
                "ROLE_STAFF",
                "ROLE_TENANT"
            ]
        },
        "enum.TenantType": {
            "type": "string",
            "enum": [
                "PERSONAL",
                "BUSINESS",
                "FOOD",
                "BEVERAGE",
                "FB"
            ],
            "x-enum-varnames": [
                "TENANT_PERSONAL",
                "TENANT_BUSINESS",
                "RESTAURANT_FOOD",
                "RESTAURANT_BEVERAGE",
                "RESTAURANT_FOOD_AND_BEVERAGE"
            ]
        },
        "enum.UserStatus": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "INACTIVE",
                "PENDING",
                "LOCKED",
                "DELETED"
            ],
            "x-enum-varnames": [
                "USER_ACTIVE",
                "USER_INACTIVE",
                "USER_PENDING",
                "USER_LOCKED",
                "USER_DELETED"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "FB Chain Management API",
	Description:      "API Documentation for FB Chain Management API - Developed by Ducking Team",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
