// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "summary": "Ping",
                "responses": {}
            }
        },
        "/admin/subscription": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create subscription API",
                "parameters": [
                    {
                        "description": "CreateSubscription body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.CreateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/client.SubscriptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/signin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Sign in API",
                "parameters": [
                    {
                        "description": "SignIn body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.SignInResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/signup/tenant": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Tenant sign up API",
                "parameters": [
                    {
                        "description": "TenantSignUp body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.TenantSignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.TenantResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        },
        "/tenant/order": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Pay subscription API",
                "parameters": [
                    {
                        "description": "PaySubscription body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.PaySubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/client.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        },
        "/tenant/restaurant": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create restaurant API",
                "parameters": [
                    {
                        "description": "CreateRestaurant body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.CreateRestaurantRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/client.RestaurantResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "client.CreateRestaurantRequest": {
            "type": "object",
            "required": [
                "location",
                "name",
                "notes",
                "postalCode",
                "type"
            ],
            "properties": {
                "contactEmail": {
                    "type": "string"
                },
                "contactPhone": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "client.CreateSubscriptionRequest": {
            "type": "object",
            "required": [
                "name",
                "price"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "durationMonth": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                }
            }
        },
        "client.OrderResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "orderDate": {
                    "type": "string"
                },
                "restaurantId": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/enum.OrderStatus"
                },
                "tenantId": {
                    "type": "integer"
                }
            }
        },
        "client.PaySubscriptionRequest": {
            "type": "object",
            "required": [
                "restaurantId",
                "subscriptionId"
            ],
            "properties": {
                "restaurantId": {
                    "type": "integer"
                },
                "subscriptionId": {
                    "type": "integer"
                }
            }
        },
        "client.RestaurantResponse": {
            "type": "object",
            "properties": {
                "avgRating": {
                    "type": "number"
                },
                "contactEmail": {
                    "type": "string"
                },
                "contactPhone": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "subscriptionId": {
                    "type": "integer"
                },
                "tenantId": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "client.SignInRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "client.SignInResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "lastLogin": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "client.SubscriptionResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "durationMonth": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "client.TenantResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birthdate": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/enum.Gender"
                },
                "identity": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "profileImage": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/enum.UserStatus"
                },
                "type": {
                    "$ref": "#/definitions/enum.TenantType"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "client.TenantSignUpRequest": {
            "type": "object",
            "required": [
                "address",
                "birthdate",
                "confirmPassword",
                "email",
                "firstName",
                "gender",
                "identity",
                "lastName",
                "password",
                "phone",
                "postalCode",
                "type"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "birthdate": {
                    "type": "string"
                },
                "confirmPassword": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/enum.Gender"
                },
                "identity": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "profileImage": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/enum.TenantType"
                }
            }
        },
        "enum.Gender": {
            "type": "string",
            "enum": [
                "MALE",
                "FEMALE"
            ],
            "x-enum-varnames": [
                "GENDER_MALE",
                "GENDER_FEMALE"
            ]
        },
        "enum.OrderStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "COMPLETED",
                "CANCELED"
            ],
            "x-enum-varnames": [
                "ORDER_PENDING",
                "ORDER_COMPLETED",
                "ORDER_CANCELED"
            ]
        },
        "enum.TenantType": {
            "type": "string",
            "enum": [
                "PERSONAL",
                "BUSINESS",
                "FOOD",
                "BEVERAGE",
                "FB"
            ],
            "x-enum-varnames": [
                "TENANT_PERSONAL",
                "TENANT_BUSINESS",
                "RESTAURANT_FOOD",
                "RESTAURANT_BEVERAGE",
                "RESTAURANT_FOOD_AND_BEVERAGE"
            ]
        },
        "enum.UserStatus": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "INACTIVE",
                "PENDING",
                "LOCKED",
                "DELETED"
            ],
            "x-enum-varnames": [
                "USER_ACTIVE",
                "USER_INACTIVE",
                "USER_PENDING",
                "USER_LOCKED",
                "USER_DELETED"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "FB Chain Management API",
	Description:      "API Documentation for FB Chain Management API - Developed by Ducking Team",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
